{{- if .Values.browserless.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "browserless.fullname" . }}-secret
  labels:
    {{- include "browserless.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.browserless.token | b64enc }}
{{- end }}